Repository devmalik7/Code_Script, pull requests merged in 2025-10, with the labels that each got.

#5 Add Digita-Clock project
  DigitalClock/CONTRIBUTING.md
  DigitalClock/README.md
  DigitalClock/digital_clock.html
Labels: javascript, hacktoberfest-accepted, hacktoberfest

#14 Reorganised the files
  Java/Java/RandomPasswordGenerator in java/Images/.png
  Java/Java/RandomPasswordGenerator in java/RandomPasswordGenerator.java
  Java/Java/Readme.md
  Python/app.py
  WebDev/DigitalClock/CONTRIBUTING.md
  WebDev/DigitalClock/README.md
  WebDev/DigitalClock/digital_clock.html
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest

#18 Dice rolling simulator implemented.
  Javascript/Dice Rolling Simulator/Dice.mp4
  Javascript/Dice Rolling Simulator/README.md
  Javascript/Dice Rolling Simulator/index.html
  Javascript/Dice Rolling Simulator/script.js
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#29 Text Summarizer
  Java/Java/Text summarizer/Readme.MD
  Java/Java/Text summarizer/Screenshot 2025-10-07 042010.png
  Java/Java/Text summarizer/Text summarizer.java
  Python/Speed test Script/Speed test.py
Labels: hacktoberfest-accepted, hacktoberfest

#32 Feature/duplicate file detector issue: #8
  Python/duplicate_file_detector/README.md
  Python/duplicate_file_detector/Screenshots/Screenshot1.PNG
  Python/duplicate_file_detector/find_duplicates.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest, python, Code_Script
